name: Node CI

on:
  push:
    branches:
      - formily_next
  pull_request:
    branches:
      - formily_next

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'chore(versions)') == false
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - run: pnpm -v
      - run: pnpm install
      - name: Oxlint
        run: npx oxlint .
      - run: pnpm build
      - run: pnpm test:prod
        env:
          CI: true
          HEADLESS: false
          PROGRESS: none
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096
